### ISSUE TITLE
Scale selection box can't be clicked in ~second half

### ISSUE THREAD

**Issue by SarahIsWeird** [gregdan3/ilo-muni#20]
To open it you either have to click on the first half (Chromium only: or on the `v`) . Would be good to fix since it's not just QoL, but also important for accessibility.

Present both in Firefox and Chromium (tested on Arc)

**Comment by gregdan3** [comment]
Funny enough, the actual error wouldn't affect keyboard-centric navigation- it only affects the mouse and mouse emulation.

Uh, I achieve the spacing in the buttons with a bare span that has padding assigned. I switched that for a left pad, so the span no longer escapes the line height. My bad!
